### ISSUE TITLE
kernel is not using morph_amount

### ISSUE THREAD

**Issue by roryaronson** [gabrielburnworth/plant-detection#2]
I tried changing `morph_amount` from the default of `5` to some extremes: `1`, `10`, `100`, and `1,000`. There were no apparent changes in the output images.

Then I changed this line: `kernel = np.ones((morph_amount, morph_amount), np.uint8)`

To: `kernel = np.ones((1000, 1000), np.uint8)` and that took effect.

**Comment by gabrielburnworth** [comment]
When you are changing the morph amount, are you changing the value of the keyword argument when calling the function (i.e. ```detect_plants(image, morph=15)```?

**Comment by roryaronson** [comment]
Ah! Nope, haha. I though it was to be changed at [line 17](https://github.com/gabrielburnworth/plant-detection/blob/master/soil_image_plant_detection.py#L17)
