### ISSUE TITLE
[bug] Camera Calibration crashes in env_var_converter

### ISSUE THREAD

**Issue by jsimmonds2** [gabrielburnworth/plant-detection#8]
[This issue in FarmBot Forum](https://forum.farmbot.org/t/camera-calibration-nothing-happens/5660) describes the problem(s).

Here's a screenshot of the Raspberry Pi Serial Console when I try **`CALIBRATE`** in the WebApp Farmware **Camera Calibration**    ( I'm running FarmbotOS **`v8.2.4-rc1`** on Raspberry Pi 3 Model B Plus with USB Camera
```
[    6.454538] uvcvideo: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
```
which captures stills nicely using **`take-photo`**  :-)

Thanks

![image](https://user-images.githubusercontent.com/1224439/70296288-2a9a0f80-183e-11ea-8a12-7ef1ca5d4ba8.png)

**Comment by gabrielburnworth** [comment]
Thanks for finding this bug and providing the output! This ended up being a bug in the Web App. Here is the fix: https://github.com/FarmBot/Farmbot-Web-App/pull/1615
